# Generated by Django 5.2.12 on 2026-04-21 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0011_alter_appointment_user'),
        ('learnapp', '0002_userdetails_address_userdetails_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('doa', models.DateField()),
                ('dod', models.DateField()),
                ('room_type', models.CharField(choices=[('Common ward', 'Common ward'), ('Semi-private', 'Semi-private'), ('Private AC', 'Private AC'), ('Private Non-AC', 'Private Non-AC'), ('Deluxe', 'Deluxe')], max_length=50)),
                ('food_required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('bed_total', models.IntegerField(blank=True, null=True)),
                ('nursing_total', models.IntegerField(blank=True, null=True)),
                ('doctor_total', models.IntegerField(blank=True, null=True)),
                ('misc_total', models.IntegerField(blank=True, null=True)),
                ('room_total', models.IntegerField(blank=True, null=True)),
                ('food_total', models.IntegerField(blank=True, null=True)),
                ('medicine_total', models.IntegerField(blank=True, null=True)),
                ('grand_total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnapp.userdetails')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.treatment')),
            ],
        ),
    ]
