# Generated by Django 5.2.12 on 2026-04-13 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0011_alter_appointment_user'),
        ('learnapp', '0002_userdetails_address_userdetails_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTecnicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=100)),
                ('year_of_experience', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test', models.CharField(choices=[('CBC', 'Complete Blood Count'), ('LFT', 'Liver Function Test'), ('URINE_TOTAL', 'Urine Total Test'), ('URINE_MICRO', 'Urine Microscopic'), ('SERUM', 'Serum Routine'), ('THYROID', 'Thyroid')], max_length=100)),
                ('lab_result', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='Ongoing', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_range', models.CharField(choices=[('nil', 'Nil'), ('positive', 'Positive'), ('negative', 'Negative'), ('normal', 'Normal'), ('abnormal', 'Abnormal')], default='Nil', max_length=100)),
                ('result_desc', models.TextField()),
                ('test_cost', models.IntegerField()),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnapp.userdetails')),
                ('reffered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
            ],
        ),
    ]
