# Generated by Django 6.0.3 on 2026-04-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alldoctors',
            old_name='Lic_no',
            new_name='license_no',
        ),
        migrations.AlterField(
            model_name='alldoctors',
            name='specialized',
            field=models.CharField(choices=[('GENERAL MEDICINE', 'general medicine'), ('CARDIOLOGIST', 'cardiologist'), ('ORTHOPEDIC', 'orthopedic'), ('EYE SPECIALIST', 'eye specialist'), ('DENTIST', 'dentist'), ('OTHERS', 'others')], max_length=100),
        ),
    ]
