# Generated by Django 6.0.3 on 2026-04-08 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_lic_no_alldoctors_license_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('HEART', 'Heart'), ('ORTHO', 'Orthopedic'), ('EYE', 'Eye'), ('DENTAL', 'Dental'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
            ],
        ),
    ]
