# Generated by Django 6.0.3 on 2026-04-08 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_treatments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatments',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='doctors.alldoctors'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('10AM-12PM', '10AM-12PM'), ('12PM-2PM', '12PM-2PM'), ('4PM-6PM', '4PM-6PM')], max_length=20)),
                ('consultation_fee', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
            ],
        ),
    ]
