# Generated by Django 6.0.3 on 2026-04-08 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_treatments_doctor_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Treatments',
            new_name='Treatment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.treatment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation_fee',
            field=models.IntegerField(default=500),
        ),
    ]
