# Generated by Django 6.0.3 on 2026-04-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_rename_treatments_treatment_appointment_treatment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='consultation_fee',
            new_name='consultation_charges',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time_slot',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='doctor',
            new_name='doctorname',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctorname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alldoctors',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='treatment',
            field=models.CharField(max_length=100),
        ),
    ]
