# Generated by Django 6.0.3 on 2026-04-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_rename_consultation_fee_appointment_consultation_charges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='consultation_charges',
            new_name='consultation_fee',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctorname',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='time_slot',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='doctorname',
            new_name='doctor',
        ),
    ]
