# Generated by Django 6.0.3 on 2026-04-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_rename_consultation_charges_appointment_consultation_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='treatment',
            new_name='doctorname',
        ),
    ]
