# Generated by Django 6.0.3 on 2026-04-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_rename_doctor_appointment_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='category',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctorname',
            new_name='treatment',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation_fee',
            field=models.CharField(blank=True, default=500, max_length=100),
        ),
    ]
